services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pyautom-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./fichasSimple.json:/app/fichasSimple.json
      - ./auth:/app/auth
    networks:
      - proxy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://api-pyautom.adsoproject.dev
    container_name: pyautom-frontend
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
